# -*- coding: utf-8 -*-
"""EstruturaDeRepeticao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pyVaEyEWXVwyGFhPyj5kbIbyBNfPuCjR

1) Faça um programa que peça uma nota, entre zero e dez. Mostre uma mensagem caso o valor seja inválido e continue pedindo até que o usuário informe um valor válido.
"""

nota = float(input('Digite uma nota:  '))
while(nota <= 0 or nota >= 10):
  print('Nota invalida')
  nota = float(input('Digite novamente uma nota:  '))
print('Ok')

"""2) Faça um programa que leia um nome de usuário e a sua senha e não aceite a senha igual ao nome do usuário, mostrando uma mensagem de erro e voltando a pedir as informações."""

nome  = str(input('Digite seu nome:  '))
senha = str(input('Digite sua senha: '))

while(nome == senha):
  print('ERRO, senha e usuário devem ser diferentes')
  nome  = str(input(' Digite novamente seu nome'))
  senha = str(input(' Digite novamente sua senha: '))

print('Tudo Ok')

"""3) Faça um programa que leia e valide as seguintes informações:
Nome: maior que 3 caracteres;
Idade: entre 0 e 150;
Salário: maior que zero;
Sexo: 'f' ou 'm';
Estado Civil: 's', 'c', 'v', 'd';
"""

nome  = str(input('Digite seu nome: '))
while(len(nome) <= 3 ):
  nome = str(input('ERRO , Seu nome deve possuir mais de 3 caracteres digite novamente seu nome: '))

idade = int(input('Digite sua idade: '))
while(idade <=0 or idade>=150 ):
  idade = int(input('Erro sua idade deve ser entra 0 a 150 , digite sua idade novamente: '))

salario = float(input('Digite seu salário: '))
while(salario <=0):
  salario = float(input('Seu salário deve ser maior que 0 digite novamente seu salário: '))

sexo = str(input('Digite seu sexo: '))
while(sexo.upper() not in 'FM'):
  sexo = str(input('Sexo inválido, digite novamente seu sexo: '))

estado_civil = str(input('Digite seu estado civil: '))
while(estado_civil.upper() not in 'SCVD'):
  estado_civil = str(input('Estado Civil inválido digite novamente seu estado civil:') )

"""4) Supondo que a população de um país A seja da ordem de 80000 habitantes com uma taxa anual de crescimento de 3% e que a população de B seja 200000 habitantes com uma taxa de crescimento de 1.5%. Faça um programa que calcule e escreva o número de anos necessários para que a população do país A ultrapasse ou iguale a população do país B, mantidas as taxas de crescimento."""

paisA = 80000
paisB = 200000
ano = 0
print('Ano: ', ano)
print('PaisA: ',paisA)
print('PaisB: ',paisB)
while(paisA <= paisB):
  paisA = paisA + (paisA*0.03)
  paisB = paisB + (paisB*0.015)
  # print('Ano: ', ano)
  # print('PaisA: {:.2f}'.format(paisA))
  # print('PaisB: {:.2f} '.format(paisB))
  # print('\n')
  ano+=1

print('A populacao de PaisA sera maior que PaisB no ano: ', ano-1)
print('PaisA: {:.2f}'.format(paisA))
print('PaisB: {:.2f} '.format(paisB))

"""5) Altere o programa anterior permitindo ao usuário informar as populações e as taxas de crescimento iniciais. Valide a entrada e permita repetir a operação."""

paisA = int(input())
paisB = 200000
ano = 0
print('Ano: ', ano)
print('PaisA: ',paisA)
print('PaisB: ',paisB)
while(paisA <= paisB):
  paisA = paisA + (paisA*0.03)
  paisB = paisB + (paisB*0.015)
  # print('Ano: ', ano)
  # print('PaisA: {:.2f}'.format(paisA))
  # print('PaisB: {:.2f} '.format(paisB))
  # print('\n')
  ano+=1

print('A populacao de PaisA sera maior que PaisB no ano: ', ano-1)
print('PaisA: {:.2f}'.format(paisA))
print('PaisB: {:.2f} '.format(paisB))

"""6) Faça um programa que imprima na tela os números de 1 a 20, um abaixo do outro. Depois modifique o programa para que ele mostre os números um ao lado do outro."""

num = 1
while(num <= 20):
  print(num)
  num += 1
num2 = 1
while(num2 <= 20):
  print(num2 ,end=' ')
  num2 += 1

"""7) Faça um programa que leia 5 números e informe o maior número. """

numero = []

for i in range(5):
  numero.append(float(input('Digite um número: ')))
  
max_val = max(numero)
print('O maior valor é: ',max_val)

"""8) Faça um programa que leia 5 números e informe a soma e a média dos números."""

numero = []
soma = 0
for i in range(5):
  numero.append(float(input('Digite um número: ')))
  soma += numero[i]

media = soma / 5
print('A media dos valores digitados é: ',media)

"""9) Faça um programa que imprima na tela apenas os números ímpares entre 1 e 50."""

for i in range(1,50,2):
  print(i)

"""10) Faça um programa que receba dois números inteiros e gere os números inteiros que estão no intervalo compreendido por eles."""

j = int(input('Digite: '))
k = int(input('Digite: '))
for i in range(j+1,k,1):
  print(i)

"""11) Altere o programa anterior para mostrar no final a soma dos números."""

j = int(input('Digite: '))
k = int(input('Digite: '))
soma = 0
for i in range(j+1,k,1):
  soma += i

print(soma)

"""12) Desenvolva um gerador de tabuada, capaz de gerar a tabuada de qualquer número inteiro entre 1 a 10. O usuário deve informar de qual numero ele deseja ver a tabuada. A saída deve ser conforme o exemplo abaixo:"""

tabuada = int(input('Digite qual tabuada vc quer ver: '))
print('Tabuada do ', tabuada)
for i in range(1,11):
  print(f'{tabuada} x {i} = ', tabuada*i)

"""13) Faça um programa que peça dois números, base e expoente, calcule e mostre o primeiro número elevado ao segundo número. Não utilize a função de potência da linguagem."""

base = int(input('Digite a base: '))
expoente = int(input('Digite o expoente: '))
resultado = 1

for i in range(expoente):
  resultado *= base
  

print(resultado)

"""14) Faça um programa que peça 10 números inteiros, calcule e mostre a quantidade de números pares e a quantidade de números impares."""

par = 0
impar = 0
for i in range(10):
  num = int(input('Digite um número inteiro: '))
  if num%2 == 0:
    par += 1
  else:
    impar += 1

print(f'Existem {par} numeros pares e {impar} números impares')

"""15) A série de Fibonacci é formada pela seqüência 1,1,2,3,5,8,13,21,34,55,... Faça um programa capaz de gerar a série até o n−ésimo termo."""



"""16) A série de Fibonacci é formada pela seqüência 0,1,1,2,3,5,8,13,21,34,55,... Faça um programa que gere a série até que o valor seja maior que 500."""



"""17) Faça um programa que calcule o fatorial de um número inteiro fornecido pelo usuário. Ex.: 5!=5.4.3.2.1=120"""

