# -*- coding: utf-8 -*-
"""EstruturaSequencial.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1J2sH85mavZtAm_x96uJnlVM8FQa_KsMT

01) Faça um Programa que mostre a mensagem "Alo mundo" na tela.
"""

print('Alo mundo')

"""02) Faça um Programa que peça um número e então mostre a mensagem O número informado foi [número]."""

num = input(' Digite um numero' )
print('O número digitado foi ' , num)

"""03) Faça um Programa que peça dois números e imprima a soma."""

num1 = int(input('Digite o primeiro número'))
num2 = int(input('Digite o segundo número'))
print(num1 + num2)

"""04) Faça um Programa que peça as 4 notas bimestrais e mostre a média."""

nota1 = float(input('Digite a primeira nota: '))
nota2 = float(input('Digite a segunda nota: '))
nota3 = float(input('Digite a terceira nota: '))
nota4 = float(input('Digite a quarta nota: '))
media = (nota1 + nota2 + nota3 + nota4)
print('A media foi {:.2f}'.format(media))

"""05) Faça um Programa que converta metros para centímetros."""

metros = float(input('Digite o tamanho em metros: '))
centimetros = metros * 100
print('O tamanho em centimetros é {:.2f}cm'.format(centimetros))

"""06) Faça um Programa que peça o raio de um círculo, calcule e mostre sua área"""

raio = float(input('Digite o tamnho do raio: '))
area = 3.1415 * raio * raio
print('A area com o raio {} é {:.2f}'.format(raio, area))

"""07) Faça um Programa que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário."""

lado = float(input('Digite a area do quadrado '))
area = lado * lado
print('O dobro da area é {}'.format(area * 2))

"""08) Faça um Programa que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês."""

valor = float(input('Digite o quanto voce ganha por hora'))
horas = int(input('Digite a quantidade de horas trabalhadas no mes: '))
salario = valor * horas
print('Seu salario é {}'.format(salario))

"""09) Faça um Programa que peça a temperatura em graus Fahrenheit, transforme e mostre a temperatura em graus Celsius.
C = 5 * ((F-32) / 9).

"""

fahre = float(input('Digite a temperatura em farehnheit: '))
celsius = ((fahre-32)/9)*5
print('A temperatura {:.4f}Farehnheit é {:.2f}celsius'.format(fahre,celsius))

"""10) Faça um Programa que peça a temperatura em graus Celsius, transforme e mostre em graus Fahrenheit.

"""

celsius = float(input('Digite a temperatura em celsius: '))
fahre = ((celsius/5)*9)+32
print('A temperatura {:.4f}celsius é {:.2f}Faranheit'.format(celsius,fahre))

"""11) Faça um Programa que peça 2 números inteiros e um número real. Calcule e mostre:
-> o produto do dobro do primeiro com metade do segundo .
-> a soma do triplo do primeiro com o terceiro.
-> o terceiro elevado ao cubo.
"""

num1 = int(input('Digite o primeiro numero: '))
num2 = int(input('Digite o segundo numero: '))
num3 = float(input('Digite o terceiro numero: '))
result1 = num1*2 + num2/2
result2 = num1 * 3 + num3
result3 = num3 ** 3
print(result1)
print(result2)
print(result3)

"""12) Tendo como dados de entrada a altura de uma pessoa, construa um algoritmo que calcule seu peso ideal, usando a seguinte fórmula: (72.7*altura) - 58"""

altura = float(input('Digite sua altura em cm:  '))
peso = ((72.7*altura)/100)-58
print('Seu peso ideal é {:.2f}kg'.format(peso))

"""13) Tendo como dado de entrada a altura (h) de uma pessoa, construa um algoritmo que calcule seu peso ideal, utilizando as seguintes fórmulas:
Para homens: (72.7*h) - 58
Para mulheres: (62.1*h) - 44.7
"""

altura = float(input('Digite sua altura em cm:  '))
genero = str(input('Digite seu sexo: m para masculino e f para feminino'))
if genero == 'm':
  peso = ((72.7*altura)/100)-58
else:
  peso = ((62.1*altura)/100)-44.7

print('Seu peso ideal é: {} '.format(peso))

"""14) João Papo-de-Pescador, homem de bem, comprou um microcomputador para controlar o rendimento diário de seu trabalho. Toda vez que ele traz um peso de peixes maior que o estabelecido pelo regulamento de pesca do estado de São Paulo (50 quilos) deve pagar uma multa de R$ 4,00 por quilo excedente. João precisa que você faça um programa que leia a variável peso (peso de peixes) e calcule o excesso. Gravar na variável excesso a quantidade de quilos além do limite e na variável multa o valor da multa que João deverá pagar. Imprima os dados do programa com as mensagens adequadas."""

peso = float(input('Digite o peso dos peixes:  '))
if peso > 50:
  exc = peso - 50
  multa = 4 * exc
  print('Peso excedente a multa será de {:.3f}'.format(multa))
else:
  print('Peso ok')

"""15) Faça um Programa que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês, sabendo-se que são descontados 11% para o Imposto de Renda, 8% para o INSS e 5% para o sindicato, faça um programa que nos dê:
salário bruto.
quanto pagou ao INSS.
quanto pagou ao sindicato.
o salário líquido.
calcule os descontos e o salário líquido, conforme a tabela abaixo:
"""

valor = float(input('Quanto voce ganha por hora: '))
horas = int(input('Quantas horas vc trabalha:  '))
salariobruto = valor * horas
imposto = salariobruto * 0.11
inss = salariobruto * 0.08
sindicato = salariobruto * 0.05
descontototal = imposto + inss + sindicato
print('Salário bruto {:.2f}'.format(salariobruto))
print('INSS {:.2f} '.format(inss))
print('Imposto {:.2f} '.format(imposto))
print('Sindicato {:.2f}'.format(sindicato))
print('Total de descontos: {:.2f} '.format(descontototal))
print('Salario Líquido : {:.2f}'.format(salariobruto - descontototal))

"""16) Faça um programa para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada 3 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam R$ 80,00. Informe ao usuário a quantidades de latas de tinta a serem compradas e o preço total."""

tamanho = float(input('Digite o tamanho em metros quadrados: '))
tinta = float(tamanho/3)
qtd = tinta/18
preco = qtd * 80
print('A quantidade será de {:.1f} latas'.format(qtd))
print('O preço total será de {:.1f} R$'.format(preco))

"""17) Faça um Programa para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é de 1 litro para cada 6 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam  80,00 ou em galões de 3,6 litros, que custam  25,00.
----Informe ao usuário as quantidades de tinta a serem compradas e os respectivos preços em 3 situações: ----
-> comprar apenas latas de 18 litros;
-> comprar apenas galões de 3,6 litros;
"""

tamanho = float(input('Digite o tamanho em metros quadrados: '))
tinta = float(tamanho/6)
qtdlatagrande = tinta/18
qtdlatapequena = tinta/3.6
precolatagrande = qtdlatagrande * 80
precolatapequena = qtdlatapequena * 25
print('Será preciso comprar {:.2f} litros'.format(tinta))
print(' Preço da lata maior (18litro) será {}'.format(precolatagrande))
print('Preço da lata menor (3,6 litros) será {}'.format(precolatapequena))

"""18) Faça um programa que peça o tamanho de um arquivo para download (em MB) e a velocidade de um link de Internet (em Mbps), calcule e informe o tempo aproximado de download do arquivo usando este link (em minutos)."""

tamanho = float(input('Digite o tamanho do arquivo:  '))
velocidade = float(input('Digite a velocidade da internet: '))
tempo = tamanho / velocidade
print(f'O tempo para o download será de {tempo}')